import { Button, Container, Navbar } from 'react-bootstrap';
import { Link, NavLink } from 'react-router';
import './style/rulePage.css';
import './style/matchPage.css';

function displayCard(card, theme = "light") {
  const cardTheme = theme === "dark" ? "my-card-dark" : "my-card-light";
  return (
    <div className={`my-card ${cardTheme}`} key={card.CID || card.name}>
      <img src={card.picture.startsWith('/') ? card.picture : `${SERVER_URL}/images/${card.picture}`} className="my-card-img" alt={card.name} />
      <div className="my-card-title">{card.name}</div>
      <div className="my-card-index">
        <svg width="80" height="40" viewBox="0 0 80 40">
          <path
            d="M10,35 A30,30 0 0,1 70,35"
            fill="none"
            stroke={theme === "dark" ? "#fff" : "#1976d2"}
            strokeWidth="6"
          />
          <path
            d="M10,35 A30,30 0 0,1 70,35"
            fill="none"
            stroke={theme === "dark" ? "#7a00cc" : "#222"}
            strokeWidth="6"
            strokeDasharray={`${(card.value / 100) * 94},94`}
          />
        </svg>
        <div className="my-card-value">{card.value !== undefined ? card.value : "???"}</div>
        <div className="my-card-label">MISFORTUNE INDEX</div>
      </div>
    </div>
  );
}

const RulePage = (props) => {
    const { darkMode } = props;
    const theme = darkMode ? "dark" : "light";
    const circeCard = {
        picture: "/src/assets/circe.jpeg",
        name: "The Sorceress Circe turned you into a pig. At least you'll live an happy life (until someone puts you on the grill)",
        value: 56
    };

    return (
        <div className='justify-content-center p-3'>
            <div>
                <h1>Rules of the Game</h1>
            </div>

            <div className="row justify-content-center mt-3 mb-3 align-items-center">
                <div className="col-md-6 text-start">
                    <h2>Overview</h2>
                    <p>
                        Step into the chaos of life’s worst moments with this entertaining web game, set against the scenic backdrop of Greece! Your mission is to collect six unique cards, each depicting a hilariously horrible situation, ranging from minor mishaps to catastrophic disasters. Every card includes a name, an image, and a <strong>misfortune index</strong> from 1 (barely bad) to 100 (downright awful). Use your wits to figure out where each new situation fits within your collection and build your ultimate deck of dreadful dilemmas.
                    </p>
                </div>
                <div className="col-md-4 d-flex justify-content-center">
                    <img
                    src='/src/assets/life_in_ancient_greece.png'
                    alt="Life in Ancient Greece"
                    className="img-fluid rule-image"
                    />
                </div>
            </div>

            <div className="row justify-content-center mt-3 mb-3 align-items-center">
                <div className="col-md-4 d-flex justify-content-center">
                    {displayCard(circeCard, theme)}
                </div>
                <div className="col-md-6 text-start">
                    <h2>Playing a round</h2>
                    <p>
                        Each round begins with the player being presented with a new horrible situation, randomly generated by the server. The player is shown the name and image of the situation, but not its misfortune index.
                    </p>
                    <ul>
                        <li>The player starts with three cards, visible in their possession, sorted by their misfortune indices.</li>
                        <li>The goal is to guess where the new situation’s misfortune index fits among the existing cards.</li>
                        <li>If guessed correctly within 30 seconds, the player earns the card, which is added to their collection with full details revealed.</li>
                        <li>If the guess is incorrect or time runs out, the card is lost, and its details are not revealed.</li>
                        <li>A message informs the player of the result, and they must confirm readiness to proceed to the next round.</li>
                        <li>The card is removed from the deck after the round, regardless of success.</li>
                    </ul>
                </div>
            </div>

            <div className="row justify-content-center mt-3 mb-3 align-items-center">
                <div className="col-md-6 text-start">
                    <h2>Winning the Game</h2>
                    <p>
                    To win the game, you must collect a total of <strong>six cards</strong> by correctly placing new situations within your deck. Each correct guess adds a card to your collection and brings you closer to victory.
                    </p>

                    <p>
                    However, the game ends in defeat if you fail to correctly place <strong>three situations</strong> during the course of the game. Stay focused and strategic, your success depends on your ability to judge where each new disaster belongs. Will you rise above the chaos or let misfortune take the win?
                    </p>
                </div>
                <div className="col-md-4 d-flex justify-content-center">
                    <img
                    src='/src/assets/victory.jpeg'
                    alt="Victory"
                    className="img-fluid rule-image"
                    />
                </div>
            </div>

            <div className="row justify-content-center mt-3 mb-3 align-items-center">
                <div className="col-md-4 d-flex justify-content-center align-items-center">
                    {/* Barra del timer d'esempio a 20 secondi su 30 */}
                    <div className="w-100" style={{ maxWidth: "300px" }}>
                    <div className="row justify-content-between">
                        <div className="col-6 text-start">
                        <small>Time left:</small>
                        </div>
                        <div className="col-6 text-end">
                        <small>20s</small>
                        </div>
                    </div>
                    <div className="progress mt-1 mb-3 progress-rtl" role="progressbar" aria-valuenow={20}>
                        <div
                        className="progress-bar bg-success"
                        style={{ width: "66.67%" }} // 20/30 = 66.67%
                        ></div>
                    </div>
                    </div>
                </div>
                <div className="col-md-6 text-start">
                    <h2>Mind the Timer</h2>
                    <p>
                    Time is critical. Players have 30 seconds to position each card. The timer ensures fast-paced gameplay, adding an element of urgency and challenge. If the player doesn’t act in time, the card is forfeited.
                    </p>
                </div>
            </div>

        </div>
    );
}

export default RulePage